steps:

  # Provision CI runner
  - name: "gcr.io/cloud-builders/docker"
    args: [ "ps", "-a" ]
    dir: "tests"


  # Provision CI runner
  - name: "gcr.io/cloud-builders/docker"
    args: [ "build", "-f", "Dockerfile.ci-runner", "-t", "ci-runner", "." ]
    dir: "tests"

  # Debug
  - name: "ci-runner"
    args: [ "printenv" ]

  # Debug
  - name: "ci-runner"
    args: [ "ls", "-ltrah", "/" ]

  # Pull splunk-ansible
  - name: "ci-runner"
    args: [ "git", "clone", "https://github.com/splunk/splunk-ansible.git", "--branch", "master" ]
    
  # Run tests
  - name: "ci-runner"
    args: [ "pytest", "-sv", "tests/test_debian_9.py::TestDebian9::test_splunk_entrypoint_help" ]

  # Build Splunk image
  - name: "ci-runner"
    args: [ "make", "splunk-debian-9" ]
